### ISSUE TITLE
Lemmatizer version

### ISSUE THREAD

**Issue by Berkmann18** [openderock/extract-lemmatized-nonstop-words#1]
Is there a reason as to why the `extract-lemmatize-nonstop-words` package was completely removed from NPM and GH?
It was the best package I've found and it's gone now.

**Comment by ziaenezhad** [comment]
@Berkmann18 I just renamed that.

**Comment by Berkmann18** [comment]
@sajjad-shirazy Why? stemmers and lemmatisers are two different things.
It's also misleading to name a lemmatiser a stemmer (unless you've changed it to a stemmer).

**Comment by ziaenezhad** [comment]
@Berkmann18 Right, it's the cause I renamed it. it was stemming not lemmatizing. my goal was collecting vocabularies of a text and lemmatizing shoots some words out. eg. using lemmatizing I will lose `better` because it will transfer to `good` while I need `better` too.

**Comment by Berkmann18** [comment]
@sajjad-shirazy Ah so it wasn't even a lemmatizer when it had that name but a stemmer since the start.

**Comment by ziaenezhad** [comment]
@Berkmann18 check out: https://github.com/winkjs/wink-lemmatizer
